algoritmo "Exercício02"

var
nomeAluno  : caracter
nota  : real
quantFracos : inteiro
quantBons  : inteiro
quantOtimos : inteiro
somaNotas : real
mediaNotas : real
inicio
// Seção de Comandos 
// entrada de dados

repita
escreval("Digite o nome do aluno :" )
leia(nomeAluno)
se nomeAluno = "FIM" entao
interrompa
fimse

repita
escreval ("Digite a nota de lógica do aluno: ")
leia(nota)


ate nomeAluno = "FIM"


fimalgoritmo


